<?php 
echo "Today is : " . date("d/m/Y");
echo "<br>";
echo "Today is : " . date("d.m.Y");
echo "<br>";
echo "Today is : " . date("d-m-Y");
echo "<br>";
echo "Today is : " . date("d.m.Y H:i:s");
echo "<br>";
echo "Today is : " . date("d-m-Y H:i:s");
echo "<br>";
echo "Today is : " . date("d.m.Y H:i:s A");
echo "<br>";
echo "Today is : " . date("d-m-Y H:i:s A");
echo "<br>";
echo "Today is : " . date("d.m.Y H:i:s T");
echo  "<br>";
echo "Today is : " . date("d-m-Y H:i:s T");
echo "<br>";
echo "Today is : " . date("d.m.Y H:i:s O");
echo "<br>";
echo "Today is : " . date("d-m-Y H:i:s O");
echo "<br>";
echo "Today is : " . date("d.m.Y H:i:s P");
echo "<br>";
echo "Today is : " . date("d-m-Y H:i:s P");
echo "<br>";
echo "Today is : " . date("d.m.Y H:i:s Z");
echo "<br>";
echo "Today is : " . date("d-m-Y H:i:s Z");
echo "<br>";
echo date("d.m.Y H:i:s e");
echo "<br>";
echo "Today is : " . date("d-m-Y H:i:s e");
echo "<br>";
echo "Today is : " . date("d.m.Y H:i:s I");
echo "<br>";
echo "Today is : " . date("d-m-Y H:i:s I");
echo "<br>";
echo "Today is : " . date("d.m.Y H:i:s O");
echo "<br>";
echo "Today is : " . date("d-m-Y H:i:s O");